version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./database.db:/app/database.db
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
